// AUTH CONSTANTS
export const SET_USER_TOKEN = 'SET_USER_TOKEN';
export const LOGOUT = 'LOGOUT';
export const SET_USER_DATA = 'SET_USER_DATA';
export const RESET = 'RESET';
// POKEMONS REDUCER CONSTANTS
export const ERROR = 'ERROR';
export const SET_RENDER = 'SET_RENDER';
export const FETCHING = 'FETCHING';
export const SET_POKEMONS = 'SET_POKEMONS';
export const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT';
export const SET_POKEMONS_URL = 'SET_POKEMONS_URL';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_TYPES = 'SET_TYPES';
export const SET_CURRENT_POKEMON = 'SET_CURRENT_POKEMON';
export const SET_CURRENT_TYPE = 'SET_CURRENT_TYPE';
export const SET_PAGE_SIZE = 'SET_PAGE_SIZE';
export const SET_FAVORITE_POKEMON = 'SET_FAVORITE_POKEMON';
export const DELETE_FAVORITE_POKEMON = 'DELETE_FAVORITE_POKEMON';
export const SET_ALL_FAVORITE_POKEMONS = 'SET_ALL_FAVORITE_POKEMONS';
export const SET_FAVORITE_POKEMON_FEED = 'SET_FAVORITE_POKEMON_FEED';
export const FAVORITE_POKEMONS_IS_RENDERED = 'FAVORITE_POKEMONS_IS_RENDERED';
// PROFILE CONSTANTS
export const SET_USER_PROFILE_INFO = 'SET_USER_PROFILE_INFO';
